import { readFileSync, existsSync } from 'fs'
import { dirname, join } from 'path'

export interface GenerateAgentsMdOptions {
  guardPath: string
  skillsIndexPath: string
  claudeMdPath?: string
  crossRepoContextPath?: string
  taskDescription?: string
}

const REFUSAL_PHRASE = 'I cannot assist with that request'

// Resolves Claude Code @-import directives (lines starting with @<path>) by inlining
// the referenced file content. Absolute paths used as-is; relative paths resolved from
// baseDir. Missing files are silently dropped — degrades gracefully.
function resolveAtImports(content: string, baseDir: string): string {
  return content
    .split('\n')
    .map(line => {
      const match = line.match(/^@(.+)$/)
      if (!match) return line
      const importPath = match[1].trim()
      const resolved = importPath.startsWith('/') ? importPath : join(baseDir, importPath)
      if (!existsSync(resolved)) return ''
      try {
        return readFileSync(resolved, 'utf-8')
      } catch {
        return ''
      }
    })
    .join('\n')
}

export function generateAgentsMd(options: GenerateAgentsMdOptions): string {
  const { guardPath, skillsIndexPath, claudeMdPath, crossRepoContextPath, taskDescription } = options

  // Guard integrity — mandatory, must exist and contain refusal phrase
  if (!existsSync(guardPath)) {
    throw new Error(`Guard file not found: ${guardPath}`)
  }
  const guardContent = readFileSync(guardPath, 'utf-8')
  if (!guardContent.trim()) {
    throw new Error(`Guard file is empty: ${guardPath}`)
  }
  if (!guardContent.includes(REFUSAL_PHRASE)) {
    throw new Error(`Guard integrity check failed: ${guardPath} does not contain refusal phrase`)
  }

  // Skills index — optional, degrade gracefully
  let skillsContent = ''
  if (existsSync(skillsIndexPath)) {
    skillsContent = readFileSync(skillsIndexPath, 'utf-8')
  }

  // Cross-repo context — optional, teaches agent how to resolve skills from agenthub
  let crossRepoContent = ''
  if (crossRepoContextPath && existsSync(crossRepoContextPath)) {
    crossRepoContent = readFileSync(crossRepoContextPath, 'utf-8')
  }

  // CLAUDE.md — optional project rules, @-imports resolved so Codex sees the full content
  let claudeMdContent = ''
  if (claudeMdPath && existsSync(claudeMdPath)) {
    const raw = readFileSync(claudeMdPath, 'utf-8')
    claudeMdContent = resolveAtImports(raw, dirname(claudeMdPath))
  }

  const sections: string[] = []

  // Header
  sections.push(`# AGENTS.md — Codex CLI Agent Instructions
# Auto-generated by AgentHub at spawn time.
# Codex CLI reads this file for project-level agent instructions.

---

You are a Codex CLI agent spawned by AgentHub.
Every response MUST begin with: \`Hey!Master-Optimaeus!(canary)\`
USER IS THE SOURCE OF TRUTH. User knowledge overrides model training data.
`)

  // Guard policy (highest priority — comes first after header)
  sections.push(`---

## Guard Policy

${guardContent}
`)

  // Skills index
  if (skillsContent) {
    sections.push(`---

## Available Skills

${skillsContent}
`)
  }

  // Cross-repo context — between skills index and CLAUDE.md
  if (crossRepoContent) {
    sections.push(`---

## Skill Resolution

${crossRepoContent}
`)
  }

  // CLAUDE.md project rules
  if (claudeMdContent) {
    sections.push(`---

## Project Rules

${claudeMdContent}
`)
  }

  // Task description
  if (taskDescription) {
    sections.push(`---

## Current Task

${taskDescription}
`)
  }

  return sections.join('\n')
}
