import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import log from 'electron-log/main'
import type Database from 'better-sqlite3'
import type { Project } from '../../shared/types/project.types'
import { getProjectById } from '../db/queries/projects.queries'
import { getLearningsByProject, getRecentCompletedSBARs } from '../db/queries/workspace-memory.queries'
import type { SBARSummary, WorkspaceMemoryEntry } from '../db/queries/workspace-memory.queries'

const MAX_BYTES = 8192
const LAYER1_LIMIT = 5

export function buildMarkdown(
  project: Project,
  sbars: SBARSummary[],
  learnings: WorkspaceMemoryEntry[]
): string {
  // Build initial 8KB guard state: start with full sbars array
  let trimmedSbars = [...sbars]

  // Iteratively rebuild content, popping oldest SBARs until under 8KB
  let content = ''
  while (true) {
    const workingSections: string[] = [
      `<!-- Auto-generated by agenthub. Do not edit. Regenerated on every spawn. -->\n`,
      `# Workspace Memory — ${project.name}\n`
    ]

    if (project.contextDoc) {
      workingSections.push(`## Project Context\n\n${project.contextDoc}\n`)
    }

    workingSections.push(`## Recent Session History\n`)
    if (trimmedSbars.length === 0) {
      workingSections.push(`_No completed sessions recorded yet._\n`)
    } else {
      for (const s of trimmedSbars) {
        const header = [s.sprintName, s.epicName, s.taskTitle].filter(Boolean).join(' / ')
        const date = new Date(s.completedAt).toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric'
        })
        workingSections.push(`### ${header}\nCompleted: ${date}`)
        if (s.situation) workingSections.push(s.situation)
        if (s.recommendation) workingSections.push(`→ ${s.recommendation}`)
        workingSections.push('')
      }
    }

    if (learnings.length > 0) {
      workingSections.push(`## Pinned Learnings\n`)
      for (const l of learnings) {
        const date = new Date(l.pinnedAt).toLocaleDateString('en-GB', {
          day: 'numeric',
          month: 'short',
          year: 'numeric'
        })
        workingSections.push(`- ${l.content}  _(pinned ${date})_`)
      }
      workingSections.push('')
    }

    content = workingSections.join('\n')

    // Check if under limit
    if (Buffer.byteLength(content, 'utf8') <= MAX_BYTES || trimmedSbars.length === 0) {
      break
    }

    // Pop oldest SBAR (last element; list is ordered newest-first)
    trimmedSbars = trimmedSbars.slice(0, trimmedSbars.length - 1)
  }

  // Pathological case: content still > 8KB after removing all SBARs
  // Log warning and return as-is (do not trim Layer 0: contextDoc or Layer 2: learnings)
  if (Buffer.byteLength(content, 'utf8') > MAX_BYTES) {
    log.warn(`[workspace-memory] content exceeds 8KB even after trimming all SBARs`, {
      contentBytes: Buffer.byteLength(content, 'utf8'),
      maxBytes: MAX_BYTES
    })
  }

  return content
}

export function writeWorkspaceMemory(
  db: Database.Database,
  projectId: string,
  projectPath: string
): void {
  try {
    if (!existsSync(projectPath)) {
      log.warn(`[workspace-memory] project path does not exist, skipping injection`, {
        projectId,
        projectPath
      })
      return
    }

    const project = getProjectById(db, projectId)
    if (!project) {
      log.warn(`[workspace-memory] project not found`, { projectId })
      return
    }

    const sbars = getRecentCompletedSBARs(db, projectId, LAYER1_LIMIT)
    const learnings = getLearningsByProject(db, projectId)
    const content = buildMarkdown(project, sbars, learnings)

    const claudeDir = join(projectPath, '.claude')
    mkdirSync(claudeDir, { recursive: true })
    writeFileSync(join(claudeDir, 'workspace_memory.md'), content, 'utf8')
    log.debug(`[workspace-memory] written`, { projectId, projectPath })
  } catch (err) {
    log.warn(`[workspace-memory] failed to write, spawn continues`, {
      projectId,
      error: String(err)
    })
  }
}
