import { mkdirSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import log from 'electron-log/main'
import type Database from 'better-sqlite3'
import type { Project } from '../../shared/types/project.types'
import { getProjectById } from '../db/queries/projects.queries'
import { getLearningsByProject, getRecentCompletedSBARs } from '../db/queries/workspace-memory.queries'
import type { SBARSummary, WorkspaceMemoryEntry } from '../db/queries/workspace-memory.queries'

const MAX_BYTES = 8192
const LAYER1_LIMIT = 5

export function buildMarkdown(
  project: Project,
  sbars: SBARSummary[],
  learnings: WorkspaceMemoryEntry[]
): string {
  const sections: string[] = [
    `<!-- Auto-generated by agenthub. Do not edit. Regenerated on every spawn. -->\n`,
    `# Workspace Memory — ${project.name}\n`
  ]

  if (project.contextDoc) {
    sections.push(`## Project Context\n\n${project.contextDoc}\n`)
  }

  sections.push(`## Recent Session History\n`)
  if (sbars.length === 0) {
    sections.push(`_No completed sessions recorded yet._\n`)
  } else {
    for (const s of sbars) {
      const header = [s.sprintName, s.epicName, s.taskTitle].filter(Boolean).join(' / ')
      const date = new Date(s.completedAt).toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'short',
        year: 'numeric'
      })
      sections.push(`### ${header}\nCompleted: ${date}`)
      if (s.situation) sections.push(s.situation)
      if (s.recommendation) sections.push(`→ ${s.recommendation}`)
      sections.push('')
    }
  }

  if (learnings.length > 0) {
    sections.push(`## Pinned Learnings\n`)
    for (const l of learnings) {
      const date = new Date(l.pinnedAt).toLocaleDateString('en-GB', {
        day: 'numeric',
        month: 'short',
        year: 'numeric'
      })
      sections.push(`- ${l.content}  _(pinned ${date})_`)
    }
    sections.push('')
  }

  let content = sections.join('\n')

  // Size guard: trim oldest SBAR entries until under 8 KB
  // Base case: if trimmedSbars is already empty, return as-is (no recursion)
  let trimmedSbars = [...sbars]
  while (Buffer.byteLength(content, 'utf8') > MAX_BYTES && trimmedSbars.length > 0) {
    trimmedSbars = trimmedSbars.slice(0, trimmedSbars.length - 1)
    content = buildMarkdown(project, trimmedSbars, learnings)
  }

  return content
}

export function writeWorkspaceMemory(
  db: Database.Database,
  projectId: string,
  projectPath: string
): void {
  try {
    if (!existsSync(projectPath)) {
      log.warn(`[workspace-memory] project path does not exist, skipping injection`, {
        projectId,
        projectPath
      })
      return
    }

    const project = getProjectById(db, projectId)
    if (!project) {
      log.warn(`[workspace-memory] project not found`, { projectId })
      return
    }

    const sbars = getRecentCompletedSBARs(db, projectId, LAYER1_LIMIT)
    const learnings = getLearningsByProject(db, projectId)
    const content = buildMarkdown(project, sbars, learnings)

    const claudeDir = join(projectPath, '.claude')
    mkdirSync(claudeDir, { recursive: true })
    writeFileSync(join(claudeDir, 'workspace_memory.md'), content, 'utf8')
    log.debug(`[workspace-memory] written`, { projectId, projectPath })
  } catch (err) {
    log.warn(`[workspace-memory] failed to write, spawn continues`, {
      projectId,
      error: String(err)
    })
  }
}
